apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mvns3zcck-python 
  janus-idp.io/tekton: mvns3zcck-python
  backstage.io/kubernetes-id: mvns3zcck-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mvns3zcck-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml